const PUBLIC_REGISTRATION_AUDIT_ACTION = "public_account_registered";
const PUBLIC_REGISTRATION_AUDIT_SOURCE = "clerk_user_created";
const PUBLIC_REGISTRATION_AUDIT_TARGET_TYPE = "User";

const USER_SYNC_ORGANIZATION_STATUS = {
  active: "active",
} as const;

const USER_SYNC_STAFF_MEMBER_STATUS = {
  invited: "invited",
} as const;

export {
  PUBLIC_REGISTRATION_AUDIT_ACTION,
  PUBLIC_REGISTRATION_AUDIT_SOURCE,
  PUBLIC_REGISTRATION_AUDIT_TARGET_TYPE,
  USER_SYNC_ORGANIZATION_STATUS,
  USER_SYNC_STAFF_MEMBER_STATUS,
};
